services:
  - type: web
    name: edubridge
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn edubridge.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: REQUIRE_DATABASE_URL
        value: "True"
      - key: SKIP_DOTENV
        value: "True"
      - key: ADMIN_PATH
        value: "secure-admin/"
      - key: PYTHON_VERSION
        value: "3.11.0"
