# Generated by Django 4.2.29 on 2026-03-17 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yosh', models.PositiveIntegerField(verbose_name='Yoshi')),
                ('o_qish_joyi', models.CharField(max_length=200, verbose_name="O'qish joyi")),
                ('yashash_joyi', models.CharField(choices=[('toshkent_sh', 'Toshkent shahri'), ('toshkent', 'Toshkent viloyati'), ('andijon', 'Andijon'), ('fargona', "Farg'ona"), ('namangan', 'Namangan'), ('samarqand', 'Samarqand'), ('buxoro', 'Buxoro'), ('qashqadaryo', 'Qashqadaryo'), ('surxondaryo', 'Surxondaryo'), ('jizzax', 'Jizzax'), ('sirdaryo', 'Sirdaryo'), ('navoiy', 'Navoiy'), ('xorazm', 'Xorazm'), ('qoraqalpogiston', "Qoraqalpog'iston")], max_length=100, verbose_name='Yashash joyi')),
                ('kutish', models.TextField(verbose_name='Bu dasturdan nimalarni kutasiz?')),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='student_rasmlari/')),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "O'quvchi profili",
                'verbose_name_plural': "O'quvchi profillari",
            },
        ),
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viloyat', models.CharField(choices=[('toshkent_sh', 'Toshkent shahri'), ('toshkent', 'Toshkent viloyati'), ('andijon', 'Andijon'), ('fargona', "Farg'ona"), ('namangan', 'Namangan'), ('samarqand', 'Samarqand'), ('buxoro', 'Buxoro'), ('qashqadaryo', 'Qashqadaryo'), ('surxondaryo', 'Surxondaryo'), ('jizzax', 'Jizzax'), ('sirdaryo', 'Sirdaryo'), ('navoiy', 'Navoiy'), ('xorazm', 'Xorazm'), ('qoraqalpogiston', "Qoraqalpog'iston")], max_length=50)),
                ('yonalish', models.CharField(choices=[('ielts', 'IELTS'), ('sat', 'SAT'), ('ingliz_tili', 'Ingliz tili')], max_length=50)),
                ('tajriba_yil', models.PositiveIntegerField(default=1, verbose_name='Tajriba (yil)')),
                ('haqida', models.TextField(blank=True, verbose_name="O'zi haqida")),
                ('ball', models.FloatField(blank=True, null=True, verbose_name='IELTS/SAT bali')),
                ('tajriba', models.TextField(verbose_name="O'qitish tajribangiz?")),
                ('metodologiya', models.TextField(verbose_name='Qanday metodologiya ishlatiladi?')),
                ('muvaffaqiyat', models.TextField(verbose_name="O'quvchilardagi eng katta muvaffaqiyat?")),
                ('vaqt', models.TextField(verbose_name="Dars vaqtlari qanday bo'ladi?")),
                ('maqsad', models.TextField(verbose_name="EduBridge'ga qo'shilish maqsadingiz?")),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='mentor_rasmlari/')),
                ('reytinq', models.FloatField(default=0.0)),
                ('o_quvchilar_soni', models.PositiveIntegerField(default=0)),
                ('tasdiqlangan', models.BooleanField(default=False)),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mentor profili',
                'verbose_name_plural': 'Mentor profillari',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yonalish', models.CharField(choices=[('ielts', 'IELTS'), ('sat', 'SAT'), ('ingliz_tili', 'Ingliz tili')], max_length=50)),
                ('to_langan', models.BooleanField(default=False)),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='accounts.mentorprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yozilish',
                'verbose_name_plural': 'Yozilishlar',
                'unique_together': {('student', 'mentor', 'yonalish')},
            },
        ),
    ]
