# Generated by Django 4.2.29 on 2026-03-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_paymentsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='yonalish',
            field=models.CharField(choices=[('ielts', 'IELTS'), ('sat', 'SAT'), ('ingliz_tili', 'Admission'), ('grants', 'Grants')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='yonalish',
            field=models.CharField(choices=[('ielts', 'IELTS'), ('sat', 'SAT'), ('ingliz_tili', 'Admission'), ('grants', 'Grants')], max_length=50),
        ),
    ]
