# Generated by Django 4.2.29 on 2026-03-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_enrollment_yonalish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsubmission',
            name='receipt_url',
            field=models.URLField(blank=True, verbose_name='Chek havolasi (ixtiyoriy)'),
        ),
    ]
