# Generated by Django 4.2.29 on 2026-03-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_paymentsubmission_receipt_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsubmission',
            name='method',
            field=models.CharField(choices=[('card', 'Karta')], default='card', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentsubmission',
            name='note',
            field=models.TextField(blank=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='paymentsubmission',
            name='payer_name',
            field=models.CharField(blank=True, max_length=120, verbose_name="To'lov qiluvchi"),
        ),
        migrations.AlterField(
            model_name='paymentsubmission',
            name='receipt_url',
            field=models.URLField(blank=True, verbose_name='Chek havolasi'),
        ),
        migrations.AlterField(
            model_name='paymentsubmission',
            name='transaction_ref',
            field=models.CharField(blank=True, max_length=120, verbose_name='Tranzaksiya ID'),
        ),
    ]
