# Generated by Django 4.2.29 on 2026-03-17 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yonalish', models.CharField(choices=[('ielts', 'IELTS'), ('sat', 'SAT'), ('ingliz_tili', 'Ingliz tili')], max_length=50)),
                ('narx', models.PositiveIntegerField(default=300000, help_text="So'mda (1 hafta, 3 dars, 3 soatdan)")),
                ('mentor_ulushi', models.PositiveIntegerField(default=200000, help_text="Mentorga to'lanadigan summa")),
                ('haftada_dars', models.PositiveIntegerField(default=3)),
                ('dars_davomiyligi', models.PositiveIntegerField(default=3, help_text='Soatda')),
                ('haqida', models.TextField(blank=True)),
                ('faol', models.BooleanField(default=True)),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kurslar', to='accounts.mentorprofile')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
            },
        ),
        migrations.CreateModel(
            name='FreeDars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=200)),
                ('yonalish', models.CharField(choices=[('ielts', 'IELTS'), ('sat', 'SAT'), ('ingliz_tili', 'Ingliz tili')], max_length=50)),
                ('sana', models.DateTimeField()),
                ('davomiylik', models.PositiveIntegerField(default=90, help_text='Daqiqada (1.5 soat = 90 daqiqa)')),
                ('link', models.URLField(blank=True, help_text='Zoom/Meet havolasi')),
                ('haqida', models.TextField(blank=True)),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_darslar', to='accounts.mentorprofile')),
            ],
            options={
                'verbose_name': 'Bepul dars',
                'verbose_name_plural': 'Bepul darslar',
                'ordering': ['-sana'],
            },
        ),
    ]
