# Generated by Django 4.2.29 on 2026-03-23 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freedars',
            name='yonalish',
            field=models.CharField(choices=[('ielts', 'IELTS'), ('sat', 'SAT'), ('ingliz_tili', 'Admission')], max_length=50),
        ),
        migrations.AlterField(
            model_name='kurs',
            name='yonalish',
            field=models.CharField(choices=[('ielts', 'IELTS'), ('sat', 'SAT'), ('ingliz_tili', 'Admission')], max_length=50),
        ),
    ]
