# Generated by Django 4.2.29 on 2026-03-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_freedars_yonalish_alter_kurs_yonalish'),
    ]

    operations = [
        migrations.AddField(
            model_name='freedars',
            name='platform',
            field=models.CharField(choices=[('meet', 'Google Meet'), ('zoom', 'Zoom'), ('other', 'Boshqa')], default='meet', max_length=20),
        ),
        migrations.AlterField(
            model_name='freedars',
            name='yonalish',
            field=models.CharField(choices=[('ielts', 'IELTS'), ('sat', 'SAT'), ('ingliz_tili', 'Admission'), ('grants', 'Grants')], max_length=50),
        ),
        migrations.AlterField(
            model_name='kurs',
            name='yonalish',
            field=models.CharField(choices=[('ielts', 'IELTS'), ('sat', 'SAT'), ('ingliz_tili', 'Admission'), ('grants', 'Grants')], max_length=50),
        ),
    ]
